name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.CICD_PAT_2 }}

      - name: Update Formula
        run: |
          VERSION="${{ github.event.client_payload.version }}"
          SHA256="${{ github.event.client_payload.sha256 }}"
          URL="${{ github.event.client_payload.url }}"
          
          # Update the formula
          sed -i "s/version \".*\"/version \"$VERSION\"/" Formula/stitch.rb
          sed -i "s|url \".*\"|url \"$URL\"|" Formula/stitch.rb  
          sed -i "s/sha256 \".*\"/sha256 \"$SHA256\"/" Formula/stitch.rb

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Formula/stitch.rb
          git commit -m "Update stitch formula to v${{ github.event.client_payload.version }}" || exit 0
          git push